services:
  - type: web
    name: landing-renacer
    runtime: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://landing-renacer.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: sqlite
